DROP DATABASE IF EXISTS Users;
CREATE DATABASE Users;

USE Users;
CREATE TABLE UserInfo (
	UID INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    nickname VARCHAR(50) NOT NULL
);